[project]
name = "ai-data-visualization-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Karamthot Anil Naik", email = "kanilnaik2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "ollama>=0.6.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "python-dotenv>=1.2.3",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
    "streamlit>=1.62.0",
]

[project.scripts]
ai-data-visualization-assistant = "ai_data_visualization_assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
